# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = HLang
DESTDIR = ./debug
QT += core gui widgets network
CONFIG += debug
HEADERS += ./*.h
SOURCES += ./*.cpp
FORMS += ./*.ui
